import type { HeroStyle, Service, Project, Testimonial, ProcessStep, CoverageArea } from './types';

export const HERO_STYLES: HeroStyle[] = [
  {
    id: 'modern-minimal',
    label: 'Modern Minimal',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1600&q=85&auto=format&fit=crop',
    accent: '#C8956C',
    swatches: ['#F5F5F5', '#2C2C2C', '#C8956C', '#E8E8E0'],
    description: 'Clean lines, handleless cabinetry, quartz surfaces',
    headline: 'Spaces designed for how you actually live.',
    subheadline: 'Precision-crafted kitchens and bathrooms with clean lines and lasting materials.',
  },
  {
    id: 'warm-heritage',
    label: 'Warm Heritage',
    image: 'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=1600&q=85&auto=format&fit=crop',
    accent: '#8B5E3C',
    swatches: ['#D4A574', '#5C3D1E', '#F2E8D9', '#8B7355'],
    description: 'Shaker doors, warm oak accents, belfast sinks',
    headline: 'Timeless craft, built to last generations.',
    subheadline: 'Heritage kitchens that honour traditional joinery with a modern sensibility.',
  },
  {
    id: 'industrial-edge',
    label: 'Industrial Edge',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=85&auto=format&fit=crop',
    accent: '#6B7280',
    swatches: ['#3A3A3A', '#8B8680', '#C0B9B0', '#1A1A1A'],
    description: 'Concrete worktops, steel fixtures, raw textures',
    headline: 'Unapologetically bold. Beautifully considered.',
    subheadline: 'Industrial kitchens that make a statement without sacrificing practicality.',
  },
  {
    id: 'scandi-natural',
    label: 'Scandi Natural',
    image: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=1600&q=85&auto=format&fit=crop',
    accent: '#9CAF88',
    swatches: ['#F8F4EE', '#C8B89A', '#9CAF88', '#E8DDD0'],
    description: 'Light wood, sage tones, natural stone details',
    headline: 'Calm, considered spaces that breathe.',
    subheadline: 'Scandi-inspired kitchens where natural materials do the talking.',
  },
];

export const SERVICES: Service[] = [
  {
    id: 'kitchen',
    title: 'Kitchen Design & Fit',
    description: 'From first sketch to final fitting, we manage every detail of your new kitchen.',
    fullDescription: 'Our kitchen service covers everything from initial design consultation through to full installation and handover. We work with premium suppliers for cabinetry, worktops, and appliances, ensuring a result that looks exceptional and functions perfectly for years to come.',
    includes: [
      'Full design consultation and 3D visualisation',
      'Supply of cabinetry, worktops and hardware',
      'Integrated appliance fitting',
      'Plumbing, electrics and gas coordination',
      'Tiling, flooring and decoration',
      'Full project management',
    ],
    priceRange: 'From £12,000',
    href: '/services#kitchen',
  },
  {
    id: 'bathroom',
    title: 'Bathroom Design & Fit',
    description: 'Complete bathroom transformations, from concept through to a space you love.',
    fullDescription: 'Whether you want a sleek en-suite or a full family bathroom renovation, we handle the entire project from design to completion. Our team manages every trade, so you have a single point of contact throughout.',
    includes: [
      'Design consultation and space planning',
      'Full supply of sanitaryware and fixtures',
      'Walk-in shower and wetroom installations',
      'Underfloor heating installation',
      'Full tiling and flooring',
      'Plumbing and electrics fully coordinated',
    ],
    priceRange: 'From £6,500',
    href: '/services#bathroom',
  },
  {
    id: 'utility',
    title: 'Utility & Boot Rooms',
    description: 'Hardworking spaces that earn their place in your home, designed to last.',
    fullDescription: 'A well-designed utility room transforms how your household runs. We design bespoke storage, plumbing and worktop solutions that handle the demands of daily life while still looking great.',
    includes: [
      'Bespoke storage and cabinetry design',
      'Integrated laundry appliance fitting',
      'Sink and plumbing installation',
      'Robust flooring for heavy use',
      'Boot room bench and storage solutions',
    ],
    priceRange: 'From £4,000',
    href: '/services#utility',
  },
  {
    id: 'consultation',
    title: 'Consultation & Planning',
    description: 'Not ready to commit? Start with a design consultation and a clear plan of action.',
    fullDescription: 'Our consultation service gives you everything you need to plan your project with confidence. We visit your home, take measurements, discuss your vision and produce a detailed design proposal and project estimate.',
    includes: [
      'Home visit and detailed measurement',
      'Design discussion and mood board',
      '3D design visualisation',
      'Full materials and specification guide',
      'Detailed project estimate and timeline',
    ],
    priceRange: 'From £350',
    href: '/services#consultation',
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'west-bridgford-kitchen',
    title: 'Victorian terrace, full kitchen transformation',
    location: 'West Bridgford, NG2',
    tags: ['Full strip-out', 'Bespoke cabinetry', 'Quartz worktops', 'Underfloor heating'],
    category: 'kitchen',
    coverImage: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80&auto=format&fit=crop',
  },
  {
    id: 'beeston-bathroom',
    title: 'Contemporary family bathroom with wet room',
    location: 'Beeston, NG9',
    tags: ['Walk-in shower', 'Freestanding bath', 'Heated floor', 'Full tiling'],
    category: 'bathroom',
    coverImage: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80&auto=format&fit=crop',
  },
  {
    id: 'wollaton-kitchen',
    title: 'Open-plan kitchen diner, Shaker style',
    location: 'Wollaton, NG8',
    tags: ['Shaker cabinetry', 'Island unit', 'Granite worktops', 'Bi-fold connection'],
    category: 'kitchen',
    coverImage: 'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80&auto=format&fit=crop',
  },
  {
    id: 'mapperley-en-suite',
    title: 'Luxury en-suite with walk-in shower',
    location: 'Mapperley, NG3',
    tags: ['Marble effect tiling', 'Rainhead shower', 'Double vanity', 'Heated towel rail'],
    category: 'bathroom',
    coverImage: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&q=80&auto=format&fit=crop',
  },
  {
    id: 'arnold-utility',
    title: 'Full utility and boot room renovation',
    location: 'Arnold, NG5',
    tags: ['Custom storage', 'Belfast sink', 'Integrated laundry', 'Porcelain floor'],
    category: 'utility',
    coverImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop',
  },
  {
    id: 'long-eaton-kitchen',
    title: 'Industrial-style kitchen, new build',
    location: 'Long Eaton, NG10',
    tags: ['Concrete worktops', 'Handleless doors', 'Integrated appliances', 'Pendant lighting'],
    category: 'kitchen',
    coverImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80&auto=format&fit=crop',
  },
  {
    id: 'gedling-bathroom',
    title: 'Period property bathroom with freestanding bath',
    location: 'Gedling, NG4',
    tags: ['Roll-top bath', 'Victorian tiling', 'Exposed pipework', 'Reclaimed wood'],
    category: 'bathroom',
    coverImage: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=800&q=80&auto=format&fit=crop',
  },
  {
    id: 'hucknall-kitchen',
    title: 'Scandi-inspired kitchen and breakfast room',
    location: 'Hucknall, NG15',
    tags: ['Light oak veneer', 'Quartz surfaces', 'Integrated fridge', 'Soft close throughout'],
    category: 'kitchen',
    coverImage: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=800&q=80&auto=format&fit=crop',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'sarah-t',
    quote: "Ashwood transformed our dated 1970s kitchen into something we genuinely love. The whole process was managed brilliantly and the finish is outstanding. Worth every penny.",
    name: 'Sarah T.',
    location: 'West Bridgford',
    projectType: 'Full kitchen renovation',
  },
  {
    id: 'james-m',
    quote: "We had three quotes and Ashwood were the only company that actually listened to what we wanted rather than just selling us a package. The attention to detail in the bathroom is exceptional.",
    name: 'James M.',
    location: 'Beeston',
    projectType: 'Bathroom design & fit',
  },
  {
    id: 'claire-r',
    quote: "From the first consultation to the final handover, the whole experience was professional and surprisingly stress-free. The utility room has completely changed how our house works day to day.",
    name: 'Claire R.',
    location: 'Wollaton',
    projectType: 'Utility room & kitchen',
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: '01',
    title: 'Consultation',
    description: 'We visit your home, take full measurements, and spend time understanding how you use the space. No pressure, no upselling.',
  },
  {
    number: '02',
    title: 'Design',
    description: 'Our designer produces detailed 3D visualisations and a full specification. You see exactly what you are getting before a single cabinet is ordered.',
  },
  {
    number: '03',
    title: 'Quote',
    description: 'A fully itemised, fixed quote with no hidden costs. We agree a project timeline and payment schedule that works for you.',
  },
  {
    number: '04',
    title: 'Build',
    description: 'Our installation team manages every trade on site. You have a single point of contact throughout, and we keep you updated at every stage.',
  },
  {
    number: '05',
    title: 'Handover',
    description: 'We complete a detailed walk-through before handing over the keys. All work is guaranteed, and we are on hand for any follow-up questions.',
  },
];

export const COVERAGE_AREAS: CoverageArea[] = [
  {
    id: 'nottingham-city',
    name: 'Nottingham City',
    count: 48,
    labelX: 200,
    labelY: 200,
    path: 'M160,150 L240,140 L260,180 L250,230 L210,250 L170,240 L150,200 Z',
  },
  {
    id: 'west-bridgford',
    name: 'West Bridgford',
    count: 22,
    labelX: 230,
    labelY: 290,
    path: 'M190,255 L260,245 L270,285 L250,310 L200,315 L180,290 Z',
  },
  {
    id: 'beeston',
    name: 'Beeston',
    count: 18,
    labelX: 130,
    labelY: 265,
    path: 'M100,240 L165,235 L175,265 L165,295 L120,300 L95,275 Z',
  },
  {
    id: 'wollaton',
    name: 'Wollaton',
    count: 14,
    labelX: 100,
    labelY: 200,
    path: 'M70,175 L145,170 L148,205 L140,235 L90,240 L65,215 Z',
  },
  {
    id: 'arnold',
    name: 'Arnold',
    count: 16,
    labelX: 265,
    labelY: 155,
    path: 'M245,125 L310,120 L320,155 L305,185 L255,188 L240,160 Z',
  },
  {
    id: 'mapperley',
    name: 'Mapperley',
    count: 12,
    labelX: 265,
    labelY: 205,
    path: 'M248,190 L305,185 L312,218 L295,245 L250,248 L238,220 Z',
  },
  {
    id: 'long-eaton',
    name: 'Long Eaton',
    count: 11,
    labelX: 130,
    labelY: 340,
    path: 'M100,320 L175,315 L180,350 L165,375 L110,378 L90,355 Z',
  },
  {
    id: 'hucknall',
    name: 'Hucknall',
    count: 9,
    labelX: 170,
    labelY: 90,
    path: 'M145,65 L210,62 L218,95 L205,122 L150,125 L135,100 Z',
  },
  {
    id: 'gedling',
    name: 'Gedling',
    count: 13,
    labelX: 300,
    labelY: 255,
    path: 'M278,240 L335,235 L340,268 L325,295 L280,298 L265,270 Z',
  },
  {
    id: 'carlton',
    name: 'Carlton',
    count: 10,
    labelX: 285,
    labelY: 180,
    path: 'M258,162 L320,158 L326,190 L312,215 L262,218 L248,192 Z',
  },
];

export const BEFORE_IMAGE = 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80&auto=format&fit=crop';
export const AFTER_IMAGE = 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80&auto=format&fit=crop';
